import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  backgroundImage: {
    flex: 1,
    minHeight: height,
    width: '100%',
  },
  editProfileButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 123, 255, 0.8)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 10,
  },
  editIcon: {
    width: 16,
    height: 16,
    marginRight: 5,
    tintColor: '#fff',
  },
  editProfileText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  profileSection: {
    marginTop: 80,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 15,
  },
  vipFrame: {
    position: 'absolute',
    width: 120,
    height: 120,
    zIndex: 2,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: '#FFD700',
    zIndex: 1,
  },
  userInfo: {
    alignItems: 'center',
    marginBottom: 20,
  },
  userName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  userIdContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  userId: {
    fontSize: 14,
    color: '#FFD700',
    marginRight: 10,
    fontWeight: '600',
  },
  levelBadge: {
    width: 30,
    height: 20,
  },
  userBadge: {
    fontSize: 12,
    color: '#FFA500',
    textAlign: 'center',
    marginBottom: 5,
    fontWeight: '500',
  },
  userBio: {
    fontSize: 12,
    color: '#CCCCCC',
    textAlign: 'center',
    fontWeight: '400',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    marginHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statLabel: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    marginBottom: 5,
  },
  statValue: {
    fontSize: 18,
    color: '#FFD700',
    fontWeight: 'bold',
  },
  currencyContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  currencyItem: {
    flex: 1,
    backgroundColor: 'rgba(0, 123, 255, 0.8)',
    marginHorizontal: 5,
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  currencyIcon: {
    width: 24,
    height: 24,
    marginBottom: 8,
    tintColor: '#fff',
  },
  currencyLabel: {
    fontSize: 10,
    color: '#fff',
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: 3,
  },
  currencyValue: {
    fontSize: 14,
    color: '#FFD700',
    fontWeight: 'bold',
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(0, 123, 255, 0.9)',
    marginHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 25,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  navButton: {
    alignItems: 'center',
    flex: 1,
  },
  navIcon: {
    width: 30,
    height: 30,
    marginBottom: 5,
    tintColor: '#fff',
  },
  navLabel: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  menuContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 30, 60, 0.9)',
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginBottom: 2,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#007BFF',
  },
  menuIcon: {
    width: 24,
    height: 24,
    marginRight: 15,
    tintColor: '#fff',
  },
  menuLabel: {
    flex: 1,
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  arrowIcon: {
    width: 16,
    height: 16,
    tintColor: '#007BFF',
  },
  // Gradient overlay styles (you can use react-native-linear-gradient for better gradients)
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
});

export default styles;